using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MatchmakingService.Models;

/// <summary>
/// T174/T178: Pre-generated daily curated picks for a user.
/// Generated by DailyPickGenerationService at scheduled UTC time.
/// Consumed by DailyPickStrategy when client requests candidates.
/// </summary>
[Table("daily_picks")]
public class DailyPick
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>The user who receives this pick.</summary>
    [Required]
    public int UserId { get; set; }

    /// <summary>The recommended candidate.</summary>
    [Required]
    public int CandidateUserId { get; set; }

    /// <summary>Pre-computed final score used for ranking.</summary>
    public double Score { get; set; }

    /// <summary>Rank within today's picks (1 = best).</summary>
    public int Rank { get; set; }

    /// <summary>When this pick was generated.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>When this pick expires (default: 24h after generation).</summary>
    public DateTime ExpiresAt { get; set; }

    /// <summary>Whether the user has seen/interacted with this pick.</summary>
    public bool Seen { get; set; }

    /// <summary>Whether the user swiped on this pick (left or right).</summary>
    public bool Acted { get; set; }

    // Navigation
    [ForeignKey(nameof(UserId))]
    public UserProfile? User { get; set; }

    [ForeignKey(nameof(CandidateUserId))]
    public UserProfile? Candidate { get; set; }
}
